Vagrant.configure("2") do |config|
N = 3
VAGRANT_VM_PROVIDER = "virtualbox"
ANSIBLE_RAW_SSH_ARGS = []

    (1..N).each do |machine_id|
      ANSIBLE_RAW_SSH_ARGS << "-o IdentityFile=.vagrant/machines/infra#{machine_id}/#{VAGRANT_VM_PROVIDER}/private_key"
    end

    (1..N).each do |machine_id|
	  config.vm.define "infra#{machine_id}" do |machine|
	  	machine.vm.box = "ubuntu/xenial64"
	    machine.vm.hostname = "infra#{machine_id}"
	    machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"

	    # Only execute once the Ansible provisioner,
	    # when all the machines are up and ready.
	    if machine_id == N
	      machine.vm.provision :ansible do |ansible|
	        # Disable default limit to connect to all the machines
	        ansible.limit = "all"
	        ansible.playbook = "../playbook.yml"
	        ansible.inventory_path = "../hosts"
            ansible.raw_ssh_args = ANSIBLE_RAW_SSH_ARGS
	      end
	    end
	  end
	end
end