---
# tasks file for etcd
- name: Download etcd
  get_url: url={{ etcd_download_url }}
           dest={{ etcd_download_dir }}/{{ etcd_download_filename }}
  become: true
  when: not etcd_config_only|bool

- name: Unarchive etcd
  unarchive: copy=no
             src={{ etcd_download_dir }}/{{ etcd_download_filename }}
             dest={{ etcd_download_dir }}
             creates="{{ etcd_download_dir }}/{{ etcd_release }}/etcd"
  become: true
  when: not etcd_config_only|bool

- name: Copy binaries from archive into etcd dir
  synchronize: src="{{ etcd_download_dir }}/{{ etcd_release }}/{{ item }}"
               dest="{{ etcd_dir }}"
               archive=True
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - etcd
    - etcdctl
  become: true
  when: not etcd_config_only|bool

- name: Add etcd systemd service
  template: src=etcd.service.j2
            dest=/etc/systemd/system/etcd.service
            mode=0644
  become: true
  notify:
    - Reload systemd
    - Restart etcd